[package]
name = "RustSense"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["FortiBrine"]
repository = "https://github.com/FortiBrine/RustSense"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive", "min_const_generics"] }
env_logger = "0.11.10"
hidapi = "2.6.6"
log = "0.4.32"
spin_sleep_util = "0.1.1"
