name: build-and-release.yml
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-linux:
    name: Build and upload (Linux)
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: x86_64-unknown-linux-gnu
      - name: Build and upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: RustSense
          target: x86_64-unknown-linux-gnu
          archive: rustsense-linux-amd64
          checksum: sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-windows:
    name: Build and upload (Windows via zigbuild)
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: x86_64-pc-windows-gnu
      - name: Build and upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: RustSense
          target: x86_64-pc-windows-gnu
          build-tool: cargo-zigbuild
          archive: rustsense-windows-amd64
          checksum: sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
